#!bin/bash
# Twitter Status Bot
#
#
#MESSAGE PARAMETRS

username=$1
password=$2
tweets=$3
#OPTIONS
uagent="Mozilla/4.0" #fake browser
sleeptime=0          #pause between request
if [ $(echo "$tweets" | wc -c) -gt 140 ];
  then echo "[ERROR] Less than 140, please!" && exit 1
elif [ "$tweets" == ""];
  then echo "[ERROR] No text" && exit 1
fi
touch "cookie.txt"   #add cookie file
#LOGIN TOKENS
echo "[+] Load twitter.com..." && sleep $sleeptime
initpage=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A
"$uagent" "https://mobile.twitter.com/session/new")
token=$(echo "$initpage" | grep "autenticity_token" |
sed -e 's/.*value="//' | cut -d '""' -f 1)
#CONNECT
echo "[+] Submitting form.." && sleep $sleeptime
loginpage=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A
"$uagent" -d "authenticity_token=$token&username=$username&password=$password"
"https://mobile.twitter.com/session")
#GRAB COMPOSE TWEET TOKENS
echo "[+] Getting compose tweet page..." && sleep $sleeptime
composepage=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A "$uagent" "https://mobile.twitter.com/compose/tweet")
#TWEET
echo "[+] Posting a new tweet: $tweet..." && sleep $sleeptime
tweettoken=$(echo "$composepage" | grep "authenticity_token" | sed -e 's/.*value="//' | cut -d '"' -f 1 | tail -n 1)
update=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A "$uagent" -d "authenticity_token=$tweettoken&tweet[text]=$tweet&commit=Tweet" "https://mobile.twitter.com/")
#GRAB LOGOUT TOKENS
logoutpage=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A "$uagent" "https://mobile.twitter.com/account")
#LOGOUT
echo "[+] Logging out..." && sleep $sleeptime
logouttoken=$(echo "$logoutpage" | grep "authenticity_token" | sed -e 's/.*value="//' | cut -d '"' -f 1 | tail -n 1)
logout=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A "$uagent" -d "authenticity_token=$logouttoken" "https://mobile.twitter.com/session/destroy")

rm "cookie.txt"
