#!bin/bash
# Twitter status bot

#MESSAGE PARAMETRS
username="$1"
password="$2"
tweets="$3"

#OPTIONS
uagent="Mozilla/5.0" #fake browser
sleeptime=0          #pause between request

if [ $(echo "$tweets" | wc -c) -gt 140 ];
  then echo "[ERROR] Less than 140, please!" && exit 1
elif [ "$tweets" == ""];
  then echo "[ERROR] No text" && exit 1
fi

touch "cookie.txt"   #add cookie file

#LOGIN TOKENS

echo "[+] Load twitter.com..." && sleep $sleeptime
initpage=$(curl -s -b "cookie.txt" -c "cookie.txt" -L -A
"$uagent" "https://mobile.twitter.com/session/new")
token=$(echo "$initpage" | grep "autenticity_token" |
sed -e 's/.*value="//' | cut -d '""' -f 1)

#CONNECT
